### ISSUE TITLE
Background music missing

### ISSUE THREAD

**Issue by amruyg** [Pixie1001/Battleships#10]
Background music (and some other sound effects?) are missing from the cs branch, while others work fine. I can see no build or runtime errors that would lead me to believe it's missing or misplaced assets. The NAudio branch seems to have working background music, but has other issues instead; is there a way to fix the original audio code?

**Comment by Pixie1001** [comment]
Yeah, SwinGame.Music doesn't seem to work in C#, so I just replaced it wholesale with a different system in the NAudio branch.
