### ISSUE TITLE
Remove broken "easy" difficulty option

### ISSUE THREAD

**Issue by amruyg** [Pixie1001/Battleships#3]
Currently only medium and hard AI difficulties are implemented; selecting "easy" from the menu results in hard AI being selected:
https://github.com/Pixie1001/Battleships/blob/e689f5e6e5ff7978cdd6d7fa4dc328065387ef28/src/GameController.cs#L102
While we don't have an easy AI implementation, we should remove this (incorrect) menu option.

**Comment by Pixie1001** [comment]
The easy difficulty has been added to the game, thus solving the problem.
