### ISSUE TITLE
Implement "easy" AI difficulty

### ISSUE THREAD

**Issue by amruyg** [Pixie1001/Battleships#4]
An easy AI needs to be written (in src/ModelAIEasyPlayer.cs) and added to the difficulty selector (#3). Use [the medium AI class](https://github.com/Pixie1001/Battleships/blob/e689f5e6e5ff7978cdd6d7fa4dc328065387ef28/src/Model/AIMediumPlayer.cs) as a reference. An initial implementation might simply choose at random from the remaining squares (it is not permitted to fire upon the same grid location twice). Ideally the routine would attempt to destroy ships after a successful hit, but use a suboptimal strategy when locating new ships.

**Comment by Pixie1001** [comment]
Ibrahm has pushed his changes to the repo, fixing the issue
